# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomas Kilbride
tagline:          'The hardware engineer'
description:      "I am a hardware engineer. I like to hack and tinker because that is how I learn."
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Thomas Kilbride'
  url:            https://twitter.com/kilbride_thomas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/obnauticus
