name: Thomas Kilbride
url: http://obnauticus.github.io
description: A webby that I made to shwocase my work :)

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
