# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomas
tagline:          'Hardware Guru'
description:      'I'm a hardware engineer that loves to be busy. I'm in to Freelance, open source and any development inbetween'
url:              http://obnauticus.com
baseurl:          /

author:
  name:           'Thomas Kilbride'
  url:            https://twitter.com/kilbride_thomas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/obnauticus
