name: Thomas Kilbride
description:  Imagination in progress...
exclude: [_tmp]
sass:
  sass_dir: assets/css/_sass
  style: :compressed

# url: http://nadjetey.github.io

owner:
    name: Thomas A. Kilbride
    twitter: kilbride_thomas
    github: obnauticus
    disqus_shortname: obnauticusportfolio

ga_id: UA-55011246-1
ga_username: #

permalink: /:year/:month/:title/
timezone: America/Indiana/Indianapolis

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
