# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomas
tagline:          'Hardware Guru'
description:      'A hardware developer that loves to be busy!'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Thomas Kilbride'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
